version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: sample_nginx
    volumes:
      - ./.dockerConfigs/nginx/conf.d/:/etc/nginx/conf.d
      - ./.dockerConfigs/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
