version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: sample_nginx
    volumes:
      - ./:/home/nginx/
      - ./.dockerConfigs/nginx/conf.d/:/etc/nginx/conf.d
      - ./.dockerConfigs/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  php:
    image: mohebnia/php-fpm
    container_name: sample_php
    working_dir: /home/www-data/
    volumes:
      - ./:/home/nginx/
      - ./.dockerConfigs/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99.overrides.ini
      - ./.dockerConfigs/php/xdebug.so:/usr/local/etc/php/modules/xdebug.so
